# Netlify Configuration für Next.js
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Node Version
  NODE_VERSION = "20.17.0"

# Rewrite rules für SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers für Security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

